/********************************************************************
* NoticeKU_DRS_PROTOROOTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NoticeKU_DRS_PROTOROOTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_inheritanceNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_typetableNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_memvarNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_globalNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_memfuncNoticeKU_DRS_PROTOROOTDict();
extern void G__cpp_setup_funcNoticeKU_DRS_PROTOROOTDict();
extern void G__set_cpp_environmentNoticeKU_DRS_PROTOROOTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NoticeKU_DRS_PROTOROOT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TClass;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TBuffer;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TMemberInspector;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TObject;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO;

/* STUB derived class for protected member access */
