//
// File generated by rootcint at Tue Nov 16 19:32:25 2021

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NoticeKU_DRS_PROTOROOTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NoticeKU_DRS_PROTOROOTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void NKKU_DRS_PROTO_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NKKU_DRS_PROTO(void *p = 0);
   static void *newArray_NKKU_DRS_PROTO(Long_t size, void *p);
   static void delete_NKKU_DRS_PROTO(void *p);
   static void deleteArray_NKKU_DRS_PROTO(void *p);
   static void destruct_NKKU_DRS_PROTO(void *p);
   static void streamer_NKKU_DRS_PROTO(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::NKKU_DRS_PROTO*)
   {
      ::NKKU_DRS_PROTO *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NKKU_DRS_PROTO >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NKKU_DRS_PROTO", ::NKKU_DRS_PROTO::Class_Version(), "./NoticeKU_DRS_PROTOROOT.h", 8,
                  typeid(::NKKU_DRS_PROTO), DefineBehavior(ptr, ptr),
                  &::NKKU_DRS_PROTO::Dictionary, isa_proxy, 2,
                  sizeof(::NKKU_DRS_PROTO) );
      instance.SetNew(&new_NKKU_DRS_PROTO);
      instance.SetNewArray(&newArray_NKKU_DRS_PROTO);
      instance.SetDelete(&delete_NKKU_DRS_PROTO);
      instance.SetDeleteArray(&deleteArray_NKKU_DRS_PROTO);
      instance.SetDestructor(&destruct_NKKU_DRS_PROTO);
      instance.SetStreamerFunc(&streamer_NKKU_DRS_PROTO);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::NKKU_DRS_PROTO*)
   {
      return GenerateInitInstanceLocal((::NKKU_DRS_PROTO*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NKKU_DRS_PROTO*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *NKKU_DRS_PROTO::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *NKKU_DRS_PROTO::Class_Name()
{
   return "NKKU_DRS_PROTO";
}

//______________________________________________________________________________
const char *NKKU_DRS_PROTO::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NKKU_DRS_PROTO*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NKKU_DRS_PROTO::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NKKU_DRS_PROTO*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NKKU_DRS_PROTO::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NKKU_DRS_PROTO*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NKKU_DRS_PROTO::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NKKU_DRS_PROTO*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void NKKU_DRS_PROTO::Streamer(TBuffer &R__b)
{
   // Stream an object of class NKKU_DRS_PROTO.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void NKKU_DRS_PROTO::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NKKU_DRS_PROTO.
      TClass *R__cl = ::NKKU_DRS_PROTO::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_NKKU_DRS_PROTO(void *p) {
      return  p ? new(p) ::NKKU_DRS_PROTO : new ::NKKU_DRS_PROTO;
   }
   static void *newArray_NKKU_DRS_PROTO(Long_t nElements, void *p) {
      return p ? new(p) ::NKKU_DRS_PROTO[nElements] : new ::NKKU_DRS_PROTO[nElements];
   }
   // Wrapper around operator delete
   static void delete_NKKU_DRS_PROTO(void *p) {
      delete ((::NKKU_DRS_PROTO*)p);
   }
   static void deleteArray_NKKU_DRS_PROTO(void *p) {
      delete [] ((::NKKU_DRS_PROTO*)p);
   }
   static void destruct_NKKU_DRS_PROTO(void *p) {
      typedef ::NKKU_DRS_PROTO current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NKKU_DRS_PROTO(TBuffer &buf, void *obj) {
      ((::NKKU_DRS_PROTO*)obj)->::NKKU_DRS_PROTO::Streamer(buf);
   }
} // end of namespace ROOT for class ::NKKU_DRS_PROTO

/********************************************************
* NoticeKU_DRS_PROTOROOTDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNoticeKU_DRS_PROTOROOTDict();

extern "C" void G__set_cpp_environmentNoticeKU_DRS_PROTOROOTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NoticeKU_DRS_PROTOROOT.h");
  G__cpp_reset_tagtableNoticeKU_DRS_PROTOROOTDict();
}
#include <new>
extern "C" int G__cpp_dllrevNoticeKU_DRS_PROTOROOTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NKKU_DRS_PROTO */
static int G__NoticeKU_DRS_PROTOROOTDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKKU_DRS_PROTO* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKKU_DRS_PROTO[n];
     } else {
       p = new((void*) gvp) NKKU_DRS_PROTO[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKKU_DRS_PROTO;
     } else {
       p = new((void*) gvp) NKKU_DRS_PROTO;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOopen((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOclose((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOread_DATA((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOreset((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOstart((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOstop((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOread_RUN((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOread_DATASIZE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOwrite_TRIG_DLY((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOread_TRIG_DLY((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOwrite_CALMODE((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOread_CALMODE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->KU_DRS_PROTOsend_TRIG((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NKKU_DRS_PROTO::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKKU_DRS_PROTO::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NKKU_DRS_PROTO::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NKKU_DRS_PROTO::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKKU_DRS_PROTO*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKKU_DRS_PROTO::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKKU_DRS_PROTO::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKKU_DRS_PROTO::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeKU_DRS_PROTOROOTDict_169_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKKU_DRS_PROTO::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NoticeKU_DRS_PROTOROOTDict_169_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NKKU_DRS_PROTO* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NKKU_DRS_PROTO(*(NKKU_DRS_PROTO*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NKKU_DRS_PROTO G__TNKKU_DRS_PROTO;
static int G__NoticeKU_DRS_PROTOROOTDict_169_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NKKU_DRS_PROTO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NKKU_DRS_PROTO*) (soff+(sizeof(NKKU_DRS_PROTO)*i)))->~G__TNKKU_DRS_PROTO();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NKKU_DRS_PROTO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NKKU_DRS_PROTO*) (soff))->~G__TNKKU_DRS_PROTO();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NoticeKU_DRS_PROTOROOTDict_169_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKKU_DRS_PROTO* dest = (NKKU_DRS_PROTO*) G__getstructoffset();
   *dest = *(NKKU_DRS_PROTO*) libp->para[0].ref;
   const NKKU_DRS_PROTO& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NKKU_DRS_PROTO */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNoticeKU_DRS_PROTOROOTDict {
 public:
  G__Sizep2memfuncNoticeKU_DRS_PROTOROOTDict(): p(&G__Sizep2memfuncNoticeKU_DRS_PROTOROOTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNoticeKU_DRS_PROTOROOTDict::*p)();
};

size_t G__get_sizep2memfuncNoticeKU_DRS_PROTOROOTDict()
{
  G__Sizep2memfuncNoticeKU_DRS_PROTOROOTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNoticeKU_DRS_PROTOROOTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO))) {
     NKKU_DRS_PROTO *G__Lderived;
     G__Lderived=(NKKU_DRS_PROTO*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO),G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNoticeKU_DRS_PROTOROOTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NKKU_DRS_PROTO */
static void G__setup_memvarNKKU_DRS_PROTO(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO));
   { NKKU_DRS_PROTO *p; p=(NKKU_DRS_PROTO*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNoticeKU_DRS_PROTOROOTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNKKU_DRS_PROTO(void) {
   /* NKKU_DRS_PROTO */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO));
   G__memfunc_setup("NKKU_DRS_PROTO",1140,G__NoticeKU_DRS_PROTOROOTDict_169_0_1, 105, G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOopen",1421,G__NoticeKU_DRS_PROTOROOTDict_169_0_2, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOclose",1521,G__NoticeKU_DRS_PROTOROOTDict_169_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOread_DATA",1776,G__NoticeKU_DRS_PROTOROOTDict_169_0_4, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid i - - 0 - buf_cnt "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOreset",1534,G__NoticeKU_DRS_PROTOROOTDict_169_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOstart",1545,G__NoticeKU_DRS_PROTOROOTDict_169_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOstop",1441,G__NoticeKU_DRS_PROTOROOTDict_169_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOread_RUN",1739,G__NoticeKU_DRS_PROTOROOTDict_169_0_8, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOread_DATASIZE",2091,G__NoticeKU_DRS_PROTOROOTDict_169_0_9, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOwrite_TRIG_DLY",2275,G__NoticeKU_DRS_PROTOROOTDict_169_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid i - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOread_TRIG_DLY",2132,G__NoticeKU_DRS_PROTOROOTDict_169_0_11, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOwrite_CALMODE",2138,G__NoticeKU_DRS_PROTOROOTDict_169_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid i - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOread_CALMODE",1995,G__NoticeKU_DRS_PROTOROOTDict_169_0_13, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KU_DRS_PROTOsend_TRIG",1818,G__NoticeKU_DRS_PROTOROOTDict_169_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NoticeKU_DRS_PROTOROOTDict_169_0_15, 85, G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NKKU_DRS_PROTO::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NoticeKU_DRS_PROTOROOTDict_169_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKKU_DRS_PROTO::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NoticeKU_DRS_PROTOROOTDict_169_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NKKU_DRS_PROTO::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NoticeKU_DRS_PROTOROOTDict_169_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NKKU_DRS_PROTO::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NoticeKU_DRS_PROTOROOTDict_169_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NoticeKU_DRS_PROTOROOTDict_169_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKKU_DRS_PROTO::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NoticeKU_DRS_PROTOROOTDict_169_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKKU_DRS_PROTO::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NoticeKU_DRS_PROTOROOTDict_169_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKKU_DRS_PROTO::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NoticeKU_DRS_PROTOROOTDict_169_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKKU_DRS_PROTO::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NKKU_DRS_PROTO", 1140, G__NoticeKU_DRS_PROTOROOTDict_169_0_27, (int) ('i'), G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO), -1, 0, 1, 1, 1, 0, "u 'NKKU_DRS_PROTO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NKKU_DRS_PROTO", 1266, G__NoticeKU_DRS_PROTOROOTDict_169_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NoticeKU_DRS_PROTOROOTDict_169_0_29, (int) ('u'), G__get_linked_tagnum(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO), -1, 1, 1, 1, 1, 0, "u 'NKKU_DRS_PROTO' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNoticeKU_DRS_PROTOROOTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNoticeKU_DRS_PROTOROOTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNoticeKU_DRS_PROTOROOTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO = { "NKKU_DRS_PROTO" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNoticeKU_DRS_PROTOROOTDict() {
  G__NoticeKU_DRS_PROTOROOTDictLN_TClass.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_TBuffer.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_TMemberInspector.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_TObject.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNoticeKU_DRS_PROTOROOTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NoticeKU_DRS_PROTOROOTDictLN_NKKU_DRS_PROTO),sizeof(NKKU_DRS_PROTO),-1,161024,"NKKU_DRS_PROTO wrapper class for root",G__setup_memvarNKKU_DRS_PROTO,G__setup_memfuncNKKU_DRS_PROTO);
}
extern "C" void G__cpp_setupNoticeKU_DRS_PROTOROOTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNoticeKU_DRS_PROTOROOTDict()");
  G__set_cpp_environmentNoticeKU_DRS_PROTOROOTDict();
  G__cpp_setup_tagtableNoticeKU_DRS_PROTOROOTDict();

  G__cpp_setup_inheritanceNoticeKU_DRS_PROTOROOTDict();

  G__cpp_setup_typetableNoticeKU_DRS_PROTOROOTDict();

  G__cpp_setup_memvarNoticeKU_DRS_PROTOROOTDict();

  G__cpp_setup_memfuncNoticeKU_DRS_PROTOROOTDict();
  G__cpp_setup_globalNoticeKU_DRS_PROTOROOTDict();
  G__cpp_setup_funcNoticeKU_DRS_PROTOROOTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNoticeKU_DRS_PROTOROOTDict();
  return;
}
class G__cpp_setup_initNoticeKU_DRS_PROTOROOTDict {
  public:
    G__cpp_setup_initNoticeKU_DRS_PROTOROOTDict() { G__add_setup_func("NoticeKU_DRS_PROTOROOTDict",(G__incsetup)(&G__cpp_setupNoticeKU_DRS_PROTOROOTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNoticeKU_DRS_PROTOROOTDict() { G__remove_setup_func("NoticeKU_DRS_PROTOROOTDict"); }
};
G__cpp_setup_initNoticeKU_DRS_PROTOROOTDict G__cpp_setup_initializerNoticeKU_DRS_PROTOROOTDict;

