/********************************************************************
* NoticeIBS_SIPM_DAQROOTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NoticeIBS_SIPM_DAQROOTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_inheritanceNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_typetableNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_memvarNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_globalNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_memfuncNoticeIBS_SIPM_DAQROOTDict();
extern void G__cpp_setup_funcNoticeIBS_SIPM_DAQROOTDict();
extern void G__set_cpp_environmentNoticeIBS_SIPM_DAQROOTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NoticeIBS_SIPM_DAQROOT.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_TClass;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_TBuffer;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_TMemberInspector;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_TObject;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NoticeIBS_SIPM_DAQROOTDictLN_NKIBS_SIPM_DAQ;

/* STUB derived class for protected member access */
