//
// File generated by rootcint at Sun Jan 23 15:32:21 2022

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NoticeSIPMTCBROOTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NoticeSIPMTCBROOTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void NKSIPMTCB_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NKSIPMTCB(void *p = 0);
   static void *newArray_NKSIPMTCB(Long_t size, void *p);
   static void delete_NKSIPMTCB(void *p);
   static void deleteArray_NKSIPMTCB(void *p);
   static void destruct_NKSIPMTCB(void *p);
   static void streamer_NKSIPMTCB(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NKSIPMTCB*)
   {
      ::NKSIPMTCB *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NKSIPMTCB >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NKSIPMTCB", ::NKSIPMTCB::Class_Version(), "./NoticeSIPMTCBROOT.h", 8,
                  typeid(::NKSIPMTCB), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NKSIPMTCB::Dictionary, isa_proxy, 2,
                  sizeof(::NKSIPMTCB) );
      instance.SetNew(&new_NKSIPMTCB);
      instance.SetNewArray(&newArray_NKSIPMTCB);
      instance.SetDelete(&delete_NKSIPMTCB);
      instance.SetDeleteArray(&deleteArray_NKSIPMTCB);
      instance.SetDestructor(&destruct_NKSIPMTCB);
      instance.SetStreamerFunc(&streamer_NKSIPMTCB);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NKSIPMTCB*)
   {
      return GenerateInitInstanceLocal((::NKSIPMTCB*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NKSIPMTCB*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr NKSIPMTCB::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NKSIPMTCB::Class_Name()
{
   return "NKSIPMTCB";
}

//______________________________________________________________________________
const char *NKSIPMTCB::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMTCB*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NKSIPMTCB::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMTCB*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NKSIPMTCB::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMTCB*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NKSIPMTCB::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMTCB*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void NKSIPMTCB::Streamer(TBuffer &R__b)
{
   // Stream an object of class NKSIPMTCB.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void NKSIPMTCB::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NKSIPMTCB.
      TClass *R__cl = ::NKSIPMTCB::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NKSIPMTCB(void *p) {
      return  p ? new(p) ::NKSIPMTCB : new ::NKSIPMTCB;
   }
   static void *newArray_NKSIPMTCB(Long_t nElements, void *p) {
      return p ? new(p) ::NKSIPMTCB[nElements] : new ::NKSIPMTCB[nElements];
   }
   // Wrapper around operator delete
   static void delete_NKSIPMTCB(void *p) {
      delete ((::NKSIPMTCB*)p);
   }
   static void deleteArray_NKSIPMTCB(void *p) {
      delete [] ((::NKSIPMTCB*)p);
   }
   static void destruct_NKSIPMTCB(void *p) {
      typedef ::NKSIPMTCB current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NKSIPMTCB(TBuffer &buf, void *obj) {
      ((::NKSIPMTCB*)obj)->::NKSIPMTCB::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::NKSIPMTCB

/********************************************************
* NoticeSIPMTCBROOTDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNoticeSIPMTCBROOTDict();

extern "C" void G__set_cpp_environmentNoticeSIPMTCBROOTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NoticeSIPMTCBROOT.h");
  G__cpp_reset_tagtableNoticeSIPMTCBROOTDict();
}
#include <new>
extern "C" int G__cpp_dllrevNoticeSIPMTCBROOTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NKSIPMTCB */
static int G__NoticeSIPMTCBROOTDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKSIPMTCB* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKSIPMTCB[n];
     } else {
       p = new((void*) gvp) NKSIPMTCB[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKSIPMTCB;
     } else {
       p = new((void*) gvp) NKSIPMTCB;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->USB3Init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->USB3Exit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBopen((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBclose((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBreset((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBstart_DAQ((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBstop_DAQ((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBsend_TRIG((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_RUN((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_FRAME((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_FRAME((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_SCAN_TIME((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_SCAN_TIME((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_TRIGGER_MODE((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_TRIGGER_MODE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_LINK((int) G__int(libp->para[0]), (unsigned long*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_MID((int) G__int(libp->para[0]), (unsigned long*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_DATASIZE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_DATA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_HV((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_HV((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_TEMP((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_PED((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (unsigned long) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_PSW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_PSW((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_RISETIME((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_RISETIME((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_PSD_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_PSD_DLY((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBwrite_PSD_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBread_PSD_THR((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (unsigned long) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBalign_ADC((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->SIPMTCBalign_DRAM((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NKSIPMTCB::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMTCB::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NKSIPMTCB::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NKSIPMTCB::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMTCB*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMTCB::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKSIPMTCB::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMTCB::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMTCBROOTDict_169_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKSIPMTCB::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NoticeSIPMTCBROOTDict_169_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NKSIPMTCB* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NKSIPMTCB(*(NKSIPMTCB*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NKSIPMTCB G__TNKSIPMTCB;
static int G__NoticeSIPMTCBROOTDict_169_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NKSIPMTCB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NKSIPMTCB*) (soff+(sizeof(NKSIPMTCB)*i)))->~G__TNKSIPMTCB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NKSIPMTCB*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NKSIPMTCB*) (soff))->~G__TNKSIPMTCB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NoticeSIPMTCBROOTDict_169_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKSIPMTCB* dest = (NKSIPMTCB*) G__getstructoffset();
   *dest = *(NKSIPMTCB*) libp->para[0].ref;
   const NKSIPMTCB& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NKSIPMTCB */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNoticeSIPMTCBROOTDict {
 public:
  G__Sizep2memfuncNoticeSIPMTCBROOTDict(): p(&G__Sizep2memfuncNoticeSIPMTCBROOTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNoticeSIPMTCBROOTDict::*p)();
};

size_t G__get_sizep2memfuncNoticeSIPMTCBROOTDict()
{
  G__Sizep2memfuncNoticeSIPMTCBROOTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNoticeSIPMTCBROOTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB))) {
     NKSIPMTCB *G__Lderived;
     G__Lderived=(NKSIPMTCB*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB),G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNoticeSIPMTCBROOTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NKSIPMTCB */
static void G__setup_memvarNKSIPMTCB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB));
   { NKSIPMTCB *p; p=(NKSIPMTCB*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNoticeSIPMTCBROOTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNKSIPMTCB(void) {
   /* NKSIPMTCB */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB));
   G__memfunc_setup("NKSIPMTCB",683,G__NoticeSIPMTCBROOTDict_169_0_1, 105, G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("USB3Init",689,G__NoticeSIPMTCBROOTDict_169_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("USB3Exit",695,G__NoticeSIPMTCBROOTDict_169_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBopen",964,G__NoticeSIPMTCBROOTDict_169_0_4, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBclose",1064,G__NoticeSIPMTCBROOTDict_169_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBreset",1077,G__NoticeSIPMTCBROOTDict_169_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBstart_DAQ",1397,G__NoticeSIPMTCBROOTDict_169_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBstop_DAQ",1293,G__NoticeSIPMTCBROOTDict_169_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBsend_TRIG",1361,G__NoticeSIPMTCBROOTDict_169_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_RUN",1282,G__NoticeSIPMTCBROOTDict_169_0_10, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_FRAME",1543,G__NoticeSIPMTCBROOTDict_169_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_FRAME",1400,G__NoticeSIPMTCBROOTDict_169_0_12, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_SCAN_TIME",1871,G__NoticeSIPMTCBROOTDict_169_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_SCAN_TIME",1728,G__NoticeSIPMTCBROOTDict_169_0_14, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_TRIGGER_MODE",2100,G__NoticeSIPMTCBROOTDict_169_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_TRIGGER_MODE",1957,G__NoticeSIPMTCBROOTDict_169_0_16, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_LINK",1339,G__NoticeSIPMTCBROOTDict_169_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid K - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_MID",1255,G__NoticeSIPMTCBROOTDict_169_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid K - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_DATASIZE",1634,G__NoticeSIPMTCBROOTDict_169_0_19, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_DATA",1319,G__NoticeSIPMTCBROOTDict_169_0_20, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data_size "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_HV",1338,G__NoticeSIPMTCBROOTDict_169_0_21, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch f - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_HV",1195,G__NoticeSIPMTCBROOTDict_169_0_22, 102, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_TEMP",1347,G__NoticeSIPMTCBROOTDict_169_0_23, 102, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_PED",1254,G__NoticeSIPMTCBROOTDict_169_0_24, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_THR",1418,G__NoticeSIPMTCBROOTDict_169_0_25, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_THR",1275,G__NoticeSIPMTCBROOTDict_169_0_26, 107, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_PSW",1430,G__NoticeSIPMTCBROOTDict_169_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_PSW",1287,G__NoticeSIPMTCBROOTDict_169_0_28, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_RISETIME",1790,G__NoticeSIPMTCBROOTDict_169_0_29, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_RISETIME",1647,G__NoticeSIPMTCBROOTDict_169_0_30, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_PSD_DLY",1739,G__NoticeSIPMTCBROOTDict_169_0_31, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_PSD_DLY",1596,G__NoticeSIPMTCBROOTDict_169_0_32, 107, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBwrite_PSD_THR",1744,G__NoticeSIPMTCBROOTDict_169_0_33, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch f - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBread_PSD_THR",1601,G__NoticeSIPMTCBROOTDict_169_0_34, 102, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid "
"k - - 0 - ch", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBalign_ADC",1348,G__NoticeSIPMTCBROOTDict_169_0_35, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMTCBalign_DRAM",1440,G__NoticeSIPMTCBROOTDict_169_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - sid k - - 0 - mid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NoticeSIPMTCBROOTDict_169_0_37, 85, G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NKSIPMTCB::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NoticeSIPMTCBROOTDict_169_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMTCB::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NoticeSIPMTCBROOTDict_169_0_39, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NKSIPMTCB::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NoticeSIPMTCBROOTDict_169_0_40, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NKSIPMTCB::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NoticeSIPMTCBROOTDict_169_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NoticeSIPMTCBROOTDict_169_0_45, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMTCB::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NoticeSIPMTCBROOTDict_169_0_46, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKSIPMTCB::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NoticeSIPMTCBROOTDict_169_0_47, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMTCB::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NoticeSIPMTCBROOTDict_169_0_48, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKSIPMTCB::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NKSIPMTCB", 683, G__NoticeSIPMTCBROOTDict_169_0_49, (int) ('i'), G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB), -1, 0, 1, 1, 1, 0, "u 'NKSIPMTCB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NKSIPMTCB", 809, G__NoticeSIPMTCBROOTDict_169_0_50, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NoticeSIPMTCBROOTDict_169_0_51, (int) ('u'), G__get_linked_tagnum(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB), -1, 1, 1, 1, 1, 0, "u 'NKSIPMTCB' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNoticeSIPMTCBROOTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNoticeSIPMTCBROOTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNoticeSIPMTCBROOTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB = { "NKSIPMTCB" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNoticeSIPMTCBROOTDict() {
  G__NoticeSIPMTCBROOTDictLN_TClass.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_TBuffer.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_TMemberInspector.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_TObject.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNoticeSIPMTCBROOTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NoticeSIPMTCBROOTDictLN_NKSIPMTCB),sizeof(NKSIPMTCB),-1,161024,"NKSIPMTCB wrapper class for root",G__setup_memvarNKSIPMTCB,G__setup_memfuncNKSIPMTCB);
}
extern "C" void G__cpp_setupNoticeSIPMTCBROOTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNoticeSIPMTCBROOTDict()");
  G__set_cpp_environmentNoticeSIPMTCBROOTDict();
  G__cpp_setup_tagtableNoticeSIPMTCBROOTDict();

  G__cpp_setup_inheritanceNoticeSIPMTCBROOTDict();

  G__cpp_setup_typetableNoticeSIPMTCBROOTDict();

  G__cpp_setup_memvarNoticeSIPMTCBROOTDict();

  G__cpp_setup_memfuncNoticeSIPMTCBROOTDict();
  G__cpp_setup_globalNoticeSIPMTCBROOTDict();
  G__cpp_setup_funcNoticeSIPMTCBROOTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNoticeSIPMTCBROOTDict();
  return;
}
class G__cpp_setup_initNoticeSIPMTCBROOTDict {
  public:
    G__cpp_setup_initNoticeSIPMTCBROOTDict() { G__add_setup_func("NoticeSIPMTCBROOTDict",(G__incsetup)(&G__cpp_setupNoticeSIPMTCBROOTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNoticeSIPMTCBROOTDict() { G__remove_setup_func("NoticeSIPMTCBROOTDict"); }
};
G__cpp_setup_initNoticeSIPMTCBROOTDict G__cpp_setup_initializerNoticeSIPMTCBROOTDict;

