//
// File generated by rootcint at Sun Jan 23 17:29:39 2022

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NoticeSIPMDAQROOTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NoticeSIPMDAQROOTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void NKSIPMDAQ_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NKSIPMDAQ(void *p = 0);
   static void *newArray_NKSIPMDAQ(Long_t size, void *p);
   static void delete_NKSIPMDAQ(void *p);
   static void deleteArray_NKSIPMDAQ(void *p);
   static void destruct_NKSIPMDAQ(void *p);
   static void streamer_NKSIPMDAQ(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NKSIPMDAQ*)
   {
      ::NKSIPMDAQ *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NKSIPMDAQ >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NKSIPMDAQ", ::NKSIPMDAQ::Class_Version(), "./NoticeSIPMDAQROOT.h", 8,
                  typeid(::NKSIPMDAQ), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NKSIPMDAQ::Dictionary, isa_proxy, 2,
                  sizeof(::NKSIPMDAQ) );
      instance.SetNew(&new_NKSIPMDAQ);
      instance.SetNewArray(&newArray_NKSIPMDAQ);
      instance.SetDelete(&delete_NKSIPMDAQ);
      instance.SetDeleteArray(&deleteArray_NKSIPMDAQ);
      instance.SetDestructor(&destruct_NKSIPMDAQ);
      instance.SetStreamerFunc(&streamer_NKSIPMDAQ);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NKSIPMDAQ*)
   {
      return GenerateInitInstanceLocal((::NKSIPMDAQ*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NKSIPMDAQ*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr NKSIPMDAQ::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NKSIPMDAQ::Class_Name()
{
   return "NKSIPMDAQ";
}

//______________________________________________________________________________
const char *NKSIPMDAQ::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMDAQ*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NKSIPMDAQ::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMDAQ*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NKSIPMDAQ::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMDAQ*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NKSIPMDAQ::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NKSIPMDAQ*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void NKSIPMDAQ::Streamer(TBuffer &R__b)
{
   // Stream an object of class NKSIPMDAQ.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void NKSIPMDAQ::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NKSIPMDAQ.
      TClass *R__cl = ::NKSIPMDAQ::IsA();
      if (R__cl || R__insp.IsA()) { }
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NKSIPMDAQ(void *p) {
      return  p ? new(p) ::NKSIPMDAQ : new ::NKSIPMDAQ;
   }
   static void *newArray_NKSIPMDAQ(Long_t nElements, void *p) {
      return p ? new(p) ::NKSIPMDAQ[nElements] : new ::NKSIPMDAQ[nElements];
   }
   // Wrapper around operator delete
   static void delete_NKSIPMDAQ(void *p) {
      delete ((::NKSIPMDAQ*)p);
   }
   static void deleteArray_NKSIPMDAQ(void *p) {
      delete [] ((::NKSIPMDAQ*)p);
   }
   static void destruct_NKSIPMDAQ(void *p) {
      typedef ::NKSIPMDAQ current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NKSIPMDAQ(TBuffer &buf, void *obj) {
      ((::NKSIPMDAQ*)obj)->::NKSIPMDAQ::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::NKSIPMDAQ

/********************************************************
* NoticeSIPMDAQROOTDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNoticeSIPMDAQROOTDict();

extern "C" void G__set_cpp_environmentNoticeSIPMDAQROOTDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NoticeSIPMDAQROOT.h");
  G__cpp_reset_tagtableNoticeSIPMDAQROOTDict();
}
#include <new>
extern "C" int G__cpp_dllrevNoticeSIPMDAQROOTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NKSIPMDAQ */
static int G__NoticeSIPMDAQROOTDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKSIPMDAQ* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKSIPMDAQ[n];
     } else {
       p = new((void*) gvp) NKSIPMDAQ[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NKSIPMDAQ;
     } else {
       p = new((void*) gvp) NKSIPMDAQ;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQopen((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQclose((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQread_DATASIZE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQread_FADC_DATASIZE((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQread_RUN((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQread_DATA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMDAQ*) G__getstructoffset())->SIPMDAQread_FADC_DATA((int) G__int(libp->para[0]), (unsigned long) G__int(libp->para[1])
, (char*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NKSIPMDAQ::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMDAQ::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NKSIPMDAQ::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NKSIPMDAQ::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NKSIPMDAQ*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMDAQ::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKSIPMDAQ::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NKSIPMDAQ::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NoticeSIPMDAQROOTDict_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NKSIPMDAQ::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NoticeSIPMDAQROOTDict_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NKSIPMDAQ* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NKSIPMDAQ(*(NKSIPMDAQ*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NKSIPMDAQ G__TNKSIPMDAQ;
static int G__NoticeSIPMDAQROOTDict_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NKSIPMDAQ*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NKSIPMDAQ*) (soff+(sizeof(NKSIPMDAQ)*i)))->~G__TNKSIPMDAQ();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NKSIPMDAQ*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NKSIPMDAQ*) (soff))->~G__TNKSIPMDAQ();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NoticeSIPMDAQROOTDict_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NKSIPMDAQ* dest = (NKSIPMDAQ*) G__getstructoffset();
   *dest = *(NKSIPMDAQ*) libp->para[0].ref;
   const NKSIPMDAQ& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NKSIPMDAQ */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNoticeSIPMDAQROOTDict {
 public:
  G__Sizep2memfuncNoticeSIPMDAQROOTDict(): p(&G__Sizep2memfuncNoticeSIPMDAQROOTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNoticeSIPMDAQROOTDict::*p)();
};

size_t G__get_sizep2memfuncNoticeSIPMDAQROOTDict()
{
  G__Sizep2memfuncNoticeSIPMDAQROOTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNoticeSIPMDAQROOTDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ))) {
     NKSIPMDAQ *G__Lderived;
     G__Lderived=(NKSIPMDAQ*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ),G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNoticeSIPMDAQROOTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NKSIPMDAQ */
static void G__setup_memvarNKSIPMDAQ(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ));
   { NKSIPMDAQ *p; p=(NKSIPMDAQ*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNoticeSIPMDAQROOTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNKSIPMDAQ(void) {
   /* NKSIPMDAQ */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ));
   G__memfunc_setup("NKSIPMDAQ",680,G__NoticeSIPMDAQROOTDict_169_0_1, 105, G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQopen",961,G__NoticeSIPMDAQROOTDict_169_0_2, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQclose",1061,G__NoticeSIPMDAQROOTDict_169_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQread_DATASIZE",1631,G__NoticeSIPMDAQROOTDict_169_0_4, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQread_FADC_DATASIZE",1996,G__NoticeSIPMDAQROOTDict_169_0_5, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQread_RUN",1279,G__NoticeSIPMDAQROOTDict_169_0_6, 107, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - sid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQread_DATA",1316,G__NoticeSIPMDAQROOTDict_169_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data_size "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SIPMDAQread_FADC_DATA",1681,G__NoticeSIPMDAQROOTDict_169_0_8, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - sid k - - 0 - data_size "
"C - - 0 - data", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NoticeSIPMDAQROOTDict_169_0_9, 85, G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NKSIPMDAQ::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NoticeSIPMDAQROOTDict_169_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMDAQ::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NoticeSIPMDAQROOTDict_169_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NKSIPMDAQ::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NoticeSIPMDAQROOTDict_169_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NKSIPMDAQ::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NoticeSIPMDAQROOTDict_169_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NoticeSIPMDAQROOTDict_169_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMDAQ::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NoticeSIPMDAQROOTDict_169_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKSIPMDAQ::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NoticeSIPMDAQROOTDict_169_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NKSIPMDAQ::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NoticeSIPMDAQROOTDict_169_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NKSIPMDAQ::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NKSIPMDAQ", 680, G__NoticeSIPMDAQROOTDict_169_0_21, (int) ('i'), G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ), -1, 0, 1, 1, 1, 0, "u 'NKSIPMDAQ' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NKSIPMDAQ", 806, G__NoticeSIPMDAQROOTDict_169_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NoticeSIPMDAQROOTDict_169_0_23, (int) ('u'), G__get_linked_tagnum(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ), -1, 1, 1, 1, 1, 0, "u 'NKSIPMDAQ' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNoticeSIPMDAQROOTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNoticeSIPMDAQROOTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNoticeSIPMDAQROOTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ = { "NKSIPMDAQ" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNoticeSIPMDAQROOTDict() {
  G__NoticeSIPMDAQROOTDictLN_TClass.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_TBuffer.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_TMemberInspector.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_TObject.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNoticeSIPMDAQROOTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NoticeSIPMDAQROOTDictLN_NKSIPMDAQ),sizeof(NKSIPMDAQ),-1,161024,"NKSIPMDAQ wrapper class for root",G__setup_memvarNKSIPMDAQ,G__setup_memfuncNKSIPMDAQ);
}
extern "C" void G__cpp_setupNoticeSIPMDAQROOTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNoticeSIPMDAQROOTDict()");
  G__set_cpp_environmentNoticeSIPMDAQROOTDict();
  G__cpp_setup_tagtableNoticeSIPMDAQROOTDict();

  G__cpp_setup_inheritanceNoticeSIPMDAQROOTDict();

  G__cpp_setup_typetableNoticeSIPMDAQROOTDict();

  G__cpp_setup_memvarNoticeSIPMDAQROOTDict();

  G__cpp_setup_memfuncNoticeSIPMDAQROOTDict();
  G__cpp_setup_globalNoticeSIPMDAQROOTDict();
  G__cpp_setup_funcNoticeSIPMDAQROOTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNoticeSIPMDAQROOTDict();
  return;
}
class G__cpp_setup_initNoticeSIPMDAQROOTDict {
  public:
    G__cpp_setup_initNoticeSIPMDAQROOTDict() { G__add_setup_func("NoticeSIPMDAQROOTDict",(G__incsetup)(&G__cpp_setupNoticeSIPMDAQROOTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNoticeSIPMDAQROOTDict() { G__remove_setup_func("NoticeSIPMDAQROOTDict"); }
};
G__cpp_setup_initNoticeSIPMDAQROOTDict G__cpp_setup_initializerNoticeSIPMDAQROOTDict;

